import { mutation } from "./_generated/server";
import { v } from "convex/values";
import { getCurrentUserOrThrow } from "./auth";

export const createTestUsers = mutation({
  args: {},
  handler: async (ctx) => {
    const currentUser = await getCurrentUserOrThrow(ctx);
    
    // Only allow this in development
    if (process.env.NODE_ENV === "production") {
      throw new Error("This function is only available in development");
    }

    const testUsers = [
      {
        name: "John Doe",
        email: "john@test.com",
        username: "johndoe",
        firstname: "John",
        lastname: "Doe",
        phoneNumber: "+1234567890",
        clerkId: "test_clerk_1",
        imageUrl: "https://i.pravatar.cc/150?img=1",
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      {
        name: "Jane Smith",
        email: "jane@test.com",
        username: "janesmith",
        firstname: "Jane",
        lastname: "Smith",
        phoneNumber: "+1234567891",
        clerkId: "test_clerk_2",
        imageUrl: "https://i.pravatar.cc/150?img=2",
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      {
        name: "Mike Johnson",
        email: "mike@test.com",
        username: "mikejohnson",
        firstname: "Mike",
        lastname: "Johnson",
        phoneNumber: "+1234567892",
        clerkId: "test_clerk_3",
        imageUrl: "https://i.pravatar.cc/150?img=3",
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      {
        name: "Sarah Wilson",
        email: "sarah@test.com",
        username: "sarahwilson",
        firstname: "Sarah",
        lastname: "Wilson",
        phoneNumber: "+1234567893",
        clerkId: "test_clerk_4",
        imageUrl: "https://i.pravatar.cc/150?img=4",
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      {
        name: "Alex Brown",
        email: "alex@test.com",
        username: "alexbrown",
        firstname: "Alex",
        lastname: "Brown",
        phoneNumber: "+1234567894",
        clerkId: "test_clerk_5",
        imageUrl: "https://i.pravatar.cc/150?img=5",
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      {
        name: "Emma Davis",
        email: "emma@test.com",
        username: "emmadavis",
        firstname: "Emma",
        lastname: "Davis",
        phoneNumber: "+1234567895",
        clerkId: "test_clerk_6",
        imageUrl: "https://i.pravatar.cc/150?img=6",
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      {
        name: "James Wilson",
        email: "james@test.com",
        username: "jameswilson",
        firstname: "James",
        lastname: "Wilson",
        phoneNumber: "+1234567896",
        clerkId: "test_clerk_7",
        imageUrl: "https://i.pravatar.cc/150?img=7",
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      {
        name: "Sophia Chen",
        email: "sophia@test.com",
        username: "sophiachen",
        firstname: "Sophia",
        lastname: "Chen",
        phoneNumber: "+1234567897",
        clerkId: "test_clerk_8",
        imageUrl: "https://i.pravatar.cc/150?img=8",
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      {
        name: "Lucas Martinez",
        email: "lucas@test.com",
        username: "lucasmartinez",
        firstname: "Lucas",
        lastname: "Martinez",
        phoneNumber: "+1234567898",
        clerkId: "test_clerk_9",
        imageUrl: "https://i.pravatar.cc/150?img=9",
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      {
        name: "Olivia Taylor",
        email: "olivia@test.com",
        username: "oliviataylor",
        firstname: "Olivia",
        lastname: "Taylor",
        phoneNumber: "+1234567899",
        clerkId: "test_clerk_10",
        imageUrl: "https://i.pravatar.cc/150?img=10",
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      {
        name: "Noah Anderson",
        email: "noah@test.com",
        username: "noahanderson",
        firstname: "Noah",
        lastname: "Anderson",
        phoneNumber: "+1234567900",
        clerkId: "test_clerk_11",
        imageUrl: "https://i.pravatar.cc/150?img=11",
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      {
        name: "Isabella Kim",
        email: "isabella@test.com",
        username: "isabellakim",
        firstname: "Isabella",
        lastname: "Kim",
        phoneNumber: "+1234567901",
        clerkId: "test_clerk_12",
        imageUrl: "https://i.pravatar.cc/150?img=12",
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      {
        name: "Ethan Patel",
        email: "ethan@test.com",
        username: "ethanpatel",
        firstname: "Ethan",
        lastname: "Patel",
        phoneNumber: "+1234567902",
        clerkId: "test_clerk_13",
        imageUrl: "https://i.pravatar.cc/150?img=13",
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      {
        name: "Ava Garcia",
        email: "ava@test.com",
        username: "avagarcia",
        firstname: "Ava",
        lastname: "Garcia",
        phoneNumber: "+1234567903",
        clerkId: "test_clerk_14",
        imageUrl: "https://i.pravatar.cc/150?img=14",
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      {
        name: "William Lee",
        email: "william@test.com",
        username: "williamlee",
        firstname: "William",
        lastname: "Lee",
        phoneNumber: "+1234567904",
        clerkId: "test_clerk_15",
        imageUrl: "https://i.pravatar.cc/150?img=15",
        createdAt: Date.now(),
        updatedAt: Date.now(),
      }
    ];

    const createdUsers = [];
    for (const user of testUsers) {
      const userId = await ctx.db.insert("users", user);
      createdUsers.push(userId);
    }

    return createdUsers;
  },
}); 